name: angular_ui
version: 0.5.4
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Tonis Pool <tonis.pool@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
- Francesco Cina <ufoscout@gmail.com>
- Neeraj Mittal <mittal.neeraj@gmail.com>
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.4.3 <2.0.0'
dependencies:
  angular: '>=0.12.0 <0.13.0'
dev_dependencies:
  mock: '>=0.11.0+1 <0.12.0'
  unittest: '>=0.11.0+2 <0.12.0'